//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public static class BuildParameters
	{
		public static readonly DateTime Time = new DateTime(636913747167699169, DateTimeKind.Utc);
		public static readonly string UnityVersion = "5.4.0f3";
		public static readonly string UnityPlatform = "WindowsEditor";
		public static readonly string OSVersion = "Microsoft Windows NT 10.0.17134.0";
		public static readonly string CurrentDirectory = "D:/dev/unity/t4-templates/src/GameDevWare.TextTransform.Unity";
		public static readonly string UserName = "denis";
		public static readonly bool Is64BitProcess = true;
	}
}
