//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public static class BuildParameters
	{
		public static readonly DateTime Time = new DateTime(637673867200022724, DateTimeKind.Utc);
		public static readonly string UnityVersion = "2018.4.5f1";
		public static readonly string UnityPlatform = "WindowsEditor";
		public static readonly string OSVersion = "Microsoft Windows NT 10.0.19041.0";
		public static readonly string CurrentDirectory = "D:/dev/projects/T4Templates/src/GameDevWare.TextTransform.Unity.2018";
		public static readonly string UserName = "denis";
		public static readonly string RuntimeVersion = "4.0.30319.42000";
		public static readonly bool Is64BitProcess = true;
		public static readonly string EditorApplicationPath = @"D:/apps/2018.4.5f1/Editor/Unity.exe";
	}
}
