//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All
using System.Linq;
using UnityEngine;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public sealed class MultipleResourceRequests
	{
		private ResourceRequest[] loadRequests;


		public float Progress { get { return this.loadRequests.Average(r => r.progress); } }
		public bool IsDone { get { return this.loadRequests.All(r => r.isDone); } }

		public MultipleResourceRequests()
		{
			this.loadRequests = new ResourceRequest[0];
		}
	}
}
