//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All
using System.Linq;
using UnityEngine;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public sealed class MultipleResourceRequests
	{
		private ResourceRequest[] loadRequests;

		public Texture2D _1462438978_2400px { get; private set; }
		public Texture2D save_2400px { get; private set; }
		public Texture2D _1462438735_2400px { get; private set; }

		public float Progress { get { return this.loadRequests.Average(r => r.progress); } }
		public bool IsDone { get { return this.loadRequests.All(r => r.isDone); } }

		public MultipleResourceRequests()
		{
			this.loadRequests = new ResourceRequest[3];
			this.loadRequests[0] = Resources.LoadAsync("1462438978-2400px.png", typeof(Texture2D));
			this.loadRequests[1] = Resources.LoadAsync("save-2400px.png", typeof(Texture2D));
			this.loadRequests[2] = Resources.LoadAsync("1462438735-2400px.png", typeof(Texture2D));
		}
	}
}
