//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public static class BuildParameters
	{
		public static readonly DateTime Time = new DateTime(636085166333083551, DateTimeKind.Utc);
		public static readonly string UnityVersion = "4.7.0f1";
		public static readonly string UnityPlatform = "WindowsEditor";
		public static readonly string OSVersion = "Microsoft Windows NT 10.0.10586.0";
		public static readonly string CurrentDirectory = "E:/dev/UnityAssets/t4-templates";
		public static readonly string UserName = "Denis";
		public static readonly bool Is64BitProcess = false;
	}
}
