//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
To pass parameters use following code:

UnityTemplateGenerator.RunForTemplate (
	"Assets\\Editor\\Examples\\Parameters_Example.tt", 
	parameters: new Dictionary<string, string> { 
		{ "HostResolvedParameter", "HOST_RESOLVED_VALUE" },
		{ "DeclaredParameter", "DECLARED_VALUE" }
	});

don't forget to set 'hostspecific' to 'true' in ''


HostResolvedParameter:  'HOST_RESOLVED_VALUE'
DeclaredParameter: 'DECLARED_VALUE'
*/